# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

stages:
  
- stage : Build
  variables:
    environment: QA
  jobs:    
  - job: 'Build_Stage_Job1'    
    displayName: 'Env $(environment)'
    steps:
    - script: echo "stage1, job1, step1  For App $(appname) for Env $(environment)"
    - script: echo "stage1, job1, step2"
  - job: 'Build_Stage_Job2'    
    steps:    
    - script: echo "stage1, job2, step1"
    - script: echo "stage1, job2, step2"

- stage : Test
  dependsOn: Build
  jobs:
  - job: 'Test_Stage_Job1'
    steps:
    - script: echo "stage Test, job1, step1"    


- stage : UAT
  dependsOn: Build
  jobs:
  - job: 'UAT_Stage_Job1'
    steps:
    - script: echo "UAT Test, job1, step1"     