# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default


jobs: 

- job: Job1
  steps:
  - script: Step 1
    displayName: 'Step 1'
  - script: Step 2
    displayName: 'Step 2'

- job: Job2
  steps:
  - script: Step 1
    displayName: 'Step 1'
  - script: Step 2
    displayName: 'Step 2'
