# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

stages:
  
- stage : Build
  variables:
    environment: QA
  jobs:    
  - job: 'Build_Stage_Job1'        
    steps:
    - script: Dir $(System.DefaultWorkingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - script: Dir $(Build.ArtifactStagingDirectory)
