# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default


jobs: 

- job: Job1
  steps:
  - script: echo 'Job1 Step 1'
    displayName: 'Step 1'
  - script: echo 'Job1 Step 2'
    displayName: 'Step 2'

- job: Job2
  dependsOn: Job3
  steps:
  - script: echo 'Job2 Step 1'
    displayName: 'Step 1'
  - script: echo 'Job2 Step 2'
    displayName: 'Step 2'

- job: Job3
  dependsOn: Job1
  steps:
  - script: echo 'Job3 Step 1'
    displayName: 'Step 1'
  