# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: default

stages:
  - stage: DevStage
    jobs:
    - deployment: Dev Deploy Job
      environment: Develop

  - stage: QAStage
    jobs:
    - deployment: QA Deploy Job
      environment: QA



