# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: default

stages:
- stage: DevStage
  jobs:
  - deployment: DevDeployJob
    environment: Develop
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying on DEV"

- stage: QAStage
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying on QA"



